/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatarSlugRouteImport } from './routes/candidatar.$slug'
import { Route as AuthenticatedVagasRouteImport } from './routes/_authenticated/vagas'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCandidatosRouteImport } from './routes/_authenticated/candidatos'
import { Route as AuthenticatedCandidatoRouteImport } from './routes/_authenticated/candidato'
import { Route as AuthenticatedCandidatosIdRouteImport } from './routes/_authenticated/candidatos.$id'
import { Route as CandidaturaSlugResultadoAppIdRouteImport } from './routes/candidatura.$slug.resultado.$appId'
import { Route as AuthenticatedCandidatosAvaliacaoIdRouteImport } from './routes/_authenticated/candidatos/avaliacao.$id'

const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatarSlugRoute = CandidatarSlugRouteImport.update({
  id: '/candidatar/$slug',
  path: '/candidatar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVagasRoute = AuthenticatedVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidatosRoute = AuthenticatedCandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatoRoute = AuthenticatedCandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatosIdRoute =
  AuthenticatedCandidatosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidatosRoute,
  } as any)
const CandidaturaSlugResultadoAppIdRoute =
  CandidaturaSlugResultadoAppIdRouteImport.update({
    id: '/candidatura/$slug/resultado/$appId',
    path: '/candidatura/$slug/resultado/$appId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCandidatosAvaliacaoIdRoute =
  AuthenticatedCandidatosAvaliacaoIdRouteImport.update({
    id: '/avaliacao/$id',
    path: '/avaliacao/$id',
    getParentRoute: () => AuthenticatedCandidatosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/candidato': typeof AuthenticatedCandidatoRoute
  '/candidatos': typeof AuthenticatedCandidatosRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/vagas': typeof AuthenticatedVagasRoute
  '/candidatar/$slug': typeof CandidatarSlugRoute
  '/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/candidatos/avaliacao/$id': typeof AuthenticatedCandidatosAvaliacaoIdRoute
  '/candidatura/$slug/resultado/$appId': typeof CandidaturaSlugResultadoAppIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/candidato': typeof AuthenticatedCandidatoRoute
  '/candidatos': typeof AuthenticatedCandidatosRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/vagas': typeof AuthenticatedVagasRoute
  '/candidatar/$slug': typeof CandidatarSlugRoute
  '/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/candidatos/avaliacao/$id': typeof AuthenticatedCandidatosAvaliacaoIdRoute
  '/candidatura/$slug/resultado/$appId': typeof CandidaturaSlugResultadoAppIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/_authenticated/candidato': typeof AuthenticatedCandidatoRoute
  '/_authenticated/candidatos': typeof AuthenticatedCandidatosRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/vagas': typeof AuthenticatedVagasRoute
  '/candidatar/$slug': typeof CandidatarSlugRoute
  '/_authenticated/candidatos/$id': typeof AuthenticatedCandidatosIdRoute
  '/_authenticated/candidatos/avaliacao/$id': typeof AuthenticatedCandidatosAvaliacaoIdRoute
  '/candidatura/$slug/resultado/$appId': typeof CandidaturaSlugResultadoAppIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/candidato'
    | '/candidatos'
    | '/configuracoes'
    | '/copiloto'
    | '/dashboard'
    | '/mapa'
    | '/relatorio'
    | '/vagas'
    | '/candidatar/$slug'
    | '/candidatos/$id'
    | '/candidatos/avaliacao/$id'
    | '/candidatura/$slug/resultado/$appId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/candidato'
    | '/candidatos'
    | '/configuracoes'
    | '/copiloto'
    | '/dashboard'
    | '/mapa'
    | '/relatorio'
    | '/vagas'
    | '/candidatar/$slug'
    | '/candidatos/$id'
    | '/candidatos/avaliacao/$id'
    | '/candidatura/$slug/resultado/$appId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/esqueci-senha'
    | '/_authenticated/candidato'
    | '/_authenticated/candidatos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/copiloto'
    | '/_authenticated/dashboard'
    | '/_authenticated/mapa'
    | '/_authenticated/relatorio'
    | '/_authenticated/vagas'
    | '/candidatar/$slug'
    | '/_authenticated/candidatos/$id'
    | '/_authenticated/candidatos/avaliacao/$id'
    | '/candidatura/$slug/resultado/$appId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  CandidatarSlugRoute: typeof CandidatarSlugRoute
  CandidaturaSlugResultadoAppIdRoute: typeof CandidaturaSlugResultadoAppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatar/$slug': {
      id: '/candidatar/$slug'
      path: '/candidatar/$slug'
      fullPath: '/candidatar/$slug'
      preLoaderRoute: typeof CandidatarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vagas': {
      id: '/_authenticated/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof AuthenticatedVagasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidatos': {
      id: '/_authenticated/candidatos'
      path: '/candidatos'
      fullPath: '/candidatos'
      preLoaderRoute: typeof AuthenticatedCandidatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidato': {
      id: '/_authenticated/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof AuthenticatedCandidatoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidatos/$id': {
      id: '/_authenticated/candidatos/$id'
      path: '/$id'
      fullPath: '/candidatos/$id'
      preLoaderRoute: typeof AuthenticatedCandidatosIdRouteImport
      parentRoute: typeof AuthenticatedCandidatosRoute
    }
    '/candidatura/$slug/resultado/$appId': {
      id: '/candidatura/$slug/resultado/$appId'
      path: '/candidatura/$slug/resultado/$appId'
      fullPath: '/candidatura/$slug/resultado/$appId'
      preLoaderRoute: typeof CandidaturaSlugResultadoAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/candidatos/avaliacao/$id': {
      id: '/_authenticated/candidatos/avaliacao/$id'
      path: '/avaliacao/$id'
      fullPath: '/candidatos/avaliacao/$id'
      preLoaderRoute: typeof AuthenticatedCandidatosAvaliacaoIdRouteImport
      parentRoute: typeof AuthenticatedCandidatosRoute
    }
  }
}

interface AuthenticatedCandidatosRouteChildren {
  AuthenticatedCandidatosIdRoute: typeof AuthenticatedCandidatosIdRoute
  AuthenticatedCandidatosAvaliacaoIdRoute: typeof AuthenticatedCandidatosAvaliacaoIdRoute
}

const AuthenticatedCandidatosRouteChildren: AuthenticatedCandidatosRouteChildren =
  {
    AuthenticatedCandidatosIdRoute: AuthenticatedCandidatosIdRoute,
    AuthenticatedCandidatosAvaliacaoIdRoute:
      AuthenticatedCandidatosAvaliacaoIdRoute,
  }

const AuthenticatedCandidatosRouteWithChildren =
  AuthenticatedCandidatosRoute._addFileChildren(
    AuthenticatedCandidatosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidatoRoute: typeof AuthenticatedCandidatoRoute
  AuthenticatedCandidatosRoute: typeof AuthenticatedCandidatosRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedVagasRoute: typeof AuthenticatedVagasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidatoRoute: AuthenticatedCandidatoRoute,
  AuthenticatedCandidatosRoute: AuthenticatedCandidatosRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedVagasRoute: AuthenticatedVagasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  CandidatarSlugRoute: CandidatarSlugRoute,
  CandidaturaSlugResultadoAppIdRoute: CandidaturaSlugResultadoAppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
